language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
  - echo "Commit sha - $TRAVIS_COMMIT"
  - mkdir -p dist/@turbo/root-config/$TRAVIS_COMMIT
  - mv dist/"." dist/@turbo/root-config/$TRAVIS_COMMIT
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "turbin-test"
  region: "us-east-2"
  cache-control: "max-age=31536000"
  acl: "public_read"
  local_dir: dist
  skip_cleanup: true
  on:
    branch: main