name: deploy-shell

on:
  push:
    branches:
      - main
    paths: [
      "apps/shell/**",
      ".github/**"
    ]
  
defaults:
  run:
    working-directory: apps/shell
  
jobs:
  build:
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_SHELL_DISTRIBUTION_ID: ${{ secrets.AWS_SHELL_DISTRIBUTION_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

        env:
          PRODUCTION_DOMAIN: ${{ secrets.AWS_SHELL_DOMAIN }}

      - name: Deploy To S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        run:
          echo ${{ env.AWS_ACCESS_KEY_ID }}
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: "apps/shell/dist"
          DEST_DIR: "shell"

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ env.AWS_SHELL_DISTRIBUTION_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          PATHS: '/shell/*'